version: '3'

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - PYTHONPATH=/workspace
    volumes:
      - ..:/workspace
    working_dir: /workspace/poetry_suburi
    command: poetry run uvicorn main:app --reload
    tty: true
